# Generated by Django 5.1.3 on 2024-11-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loan',
            fields=[
                ('Loan_Id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Salary', models.IntegerField()),
                ('Loan_applied_date', models.DateField()),
                ('Loan_amount', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_no', models.IntegerField()),
            ],
        ),
    ]
